source 'https://rubygems.org' do
  gem 'sinatra'
  gem 'sinatra-reloader' 
  gem 'twitter'
  gem 'sqlite3'
  gem 'bcrypt'
  gem 'nokogiri', '1.6.7.2'
  gem 'sinatra'
  gem 'thin'
  gem 'capybara'
  gem 'cucumber'
  gem 'rspec'
  gem 'simplecov'
  gem 'geocoder'
end